org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
loader_version_range=[1,)

mod_id=adminlogger
mod_name=Admin Logger
mod_license=MIT
mod_version=2.3.0
mod_group_id=com.adminlogger
mod_authors=jonatasperaza
mod_display_url=https://github.com/jonatasperaza/Minecraft-admin-logger
mod_issue_tracker_url=https://github.com/jonatasperaza/Minecraft-admin-logger/issues
mod_description=Administrative logging for Minecraft servers.
