modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/jonatasperaza/Minecraft-admin-logger/issues"

[[mods]]
modId="adminlogger"
version="1.4"
displayName="Admin Logger"
updateJSONURL="https://github.com/jonatasperaza/Minecraft-admin-logger/raw/main/update.json"
displayURL="https://github.com/jonatasperaza/Minecraft-admin-logger"
logoFile="logo.png"
credits="Forge community | Contributors"
authors="jonatasperaza"
description='''
Logs administrativos para servidores Minecraft
• Rastreamento de login/logout
• Registro de chat/comandos
• Suporte multilíngue
'''

[mods.adminlogger]
catalogueMetadataVersion=2
configuredBackground="minecraft:textures/block/stone.png"

[mods.adminlogger.links]
website="https://github.com/jonatasperaza/Minecraft-admin-logger"
issues="https://github.com/jonatasperaza/Minecraft-admin-logger/issues"

[mods.adminlogger.badges]
library=true

[[dependencies.adminlogger]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.adminlogger]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"