modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="adminlogger"
version="1.1"
displayName="Admin Logger"
authors="jonatasperaza"
description='''
Um mod que registra ações administrativas e mensagens do chat no servidor.
'''

[[dependencies.adminlogger]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.adminlogger]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="SERVER" 